--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team06-house
  namespace: team06
  labels:
    app: team06-house
spec:
  selector:
    matchLabels:
      app: team06-house
  replicas: 1
  template:
    metadata:
      labels:
        app: team06-house
    spec:
      containers:
      - name: team06-house
        image: docker.io/ibmicpcoc/house:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: team06-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: team06-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---
