--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
--- 
kind: Pod
metadata:
  name: <team>-karma-base
  namespace: red
  labels:
     team: "red"
spec:
  containers:
  - name: ocp
    image: nginx
---
--- # Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: <team>-karma-runner
  namespace: red
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: team
            operator: In
            values:
            - "color"
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: docker.io/ibmicpcoc/karma:latest
    imagePullPolicy: Always
    env:
    - name: APP_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: COLLECTOR_CONFIG
      valueFrom: 
        configMapKeyRef:
          name: <team>-collector-config
          key: COLLECTOR_CONFIG
    - name: INSTRUCTOR_CONFIG
      valueFrom: 
        configMapKeyRef:
          name: <team>-collector-config
          key: INSTRUCTOR_CONFIG
    resources:
      requests:
        cpu: 50m
        memory: 50Mi    
---
